journals/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework import routers
from journals import views


# SET THE NAMESPACE!
app_name = 'journals'

Profilerouter = routers.DefaultRouter()
Profilerouter.register(r'profile', views.ProfileView)

urlpatterns=[
	path('', include(Profilerouter.urls)),
    url(r'^register/$',views.register, name='register'),
    url(r'^user_login/$',views.user_login, name='user_login'),
    path('entry/', views.JournalEntryView.as_view(), name='entry')
]

myJournal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from journals import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^journals/',include('journals.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

journals/models.py
"""
Each profile has a unique journal with jourrnal_id assigned to it
Each journal can have multiple entries, hence a one-to-many field from journal to entries
"""
from django.db import models
from django.contrib.auth.models import User

from django.contrib.postgres.fields import JSONField
from django.core.validators import RegexValidator

from django.conf import settings


class Profile(models.Model):
    """
    Extends user model of django.auth
    stores further information needed for a user
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )
    primary_cell = models.CharField(
        validators=[RegexValidator(regex='^.{10}$', message='Length has to be 10', code='nomatch')],
        max_length=10,
    )
    profile_pic = models.ImageField(
        upload_to='profile_pic',
        blank=True
    )

    def __str__(self):
        return self.user.username


class Journal(models.Model):
    """
    Model to keep journal for each profile
    """
    profile = models.OneToOneField(
        Profile,
        on_delete=models.CASCADE
    )


class Entry(models.Model):
    """
    Model for daily cronological entries
    A new entry is to be made every day
    Each 'daily entry' will contain key value pair of time and entry
    """
    date = models.DateField()
    entries = JSONField(
        help_text="key value pair (time, entry) for each day",
        default=dict
    )
    journal = models.ForeignKey(
        Journal,
        on_delete=models.CASCADE
    )

    class Meta:
        unique_together = ('date', 'journal')

    def add_entry(self, entry):
        """Add a new entry"""
        self.entries.update(entry)
        self.save()

journals/forms.py
from django import forms

from django.contrib.auth.models import User
from django.core.validators import RegexValidator

from journals.models import Profile


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'password',
			'email'
		)


class UserProfileInfoForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = (
			'primary_cell',
			'profile_pic'
		)


class MakeEntryForm(forms.Form):
	entry = forms.CharField(widget=forms.Textarea(attrs={'cols': 100, 'rows': 5}))

journals/views.py
from datetime import datetime

from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import CreateAPIView
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from journals.forms import UserForm,UserProfileInfoForm, MakeEntryForm
from journals.serializers import ProfileSerializer, JournalEntrySerializer
from journals.models import Profile, Journal, Entry


class ProfileView(LoginRequiredMixin, ModelViewSet):
    serializer_class = ProfileSerializer
    queryset = Profile.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user__username=self.request.user)
        return qs


class JournalEntryView(LoginRequiredMixin, CreateAPIView):
    serializer_class = JournalEntrySerializer

    def get_serializer_context(self):
        return {'user': self.request.user.username}

    def post(self, request, **kwargs):
        if not dict(request.POST).get('entry')[0]:
            return HttpResponseRedirect(reverse('index'))
        super().post(request, kwargs)
        return HttpResponseRedirect(reverse('index'))


def index(request):
    journal = Journal.objects.filter(profile__user__username=request.user.username).first()
    entry = Entry.objects.filter(journal=journal, date=str(datetime.now().date())).first()
    return render(
        request,'index.html',
        {
            'entry_form': MakeEntryForm(),
            'entry': entry
        }
    )


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            # Create a new user
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            # Create a new profile
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('profile pic present')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            # Create a new journal for the new registered user
            Journal.objects.create(profile=profile)
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login.html', {})

journals/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">My Journal</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'journals:register' %}">Register</a></li>     
            <li><a class="navbar-link" href="{% url 'journals:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

journals/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
    	{% if not user.is_authenticated %}
		    <h1>Login / Register to start Journaling!</h1>
    	{% else %}
	    	<h2> Wassup {{ user.first_name }} !</h2>
			<form method="post" action="{% url 'journals:entry' %}">
			          {% csrf_token %}
			          {# Ask for journal entry #}
			          {{ entry_form }}
			<input type="submit" name="" value="Submit">
			</form>
				<div class="jumbotron">
					{% if entry %}
					    <b> <h3> {{entry.date}} </h3> </b> <br> <br>
					    {% for time, record in entry.entries.items %}
						    <u> {{time}} </u> : {{record}} <br>
					    {% endfor %}
					{% endif %}
				</div>
			</div>
			  </div>
    	{% endif %}
{% endblock %}

journals/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'journals:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

journals/templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}